version: '3.3'

services:
  #nginx:
  #  depends_on: 
  #    - wordpress
  #  image: nginx:1.15-alpine
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ./data/nginx:/etc/nginx/conf.d
  #    - ./data/cert/:/etc/cert
  #    - ./scripts:/bin/scripts
  db: 
    image: mysql@sha256:c358e72e100ab493a0304bda35e6f239db2ec8c9bb836d8a427ac34307d074ed
    ports:
      - "3306:3306"
    volumes:
      - zucchini_db_data:/var/lib/mysql
      - ./dbinit:/docker-entrypoint-initdb.d
      - ./scripts:/bin/scripts
    restart: always
    #entrypoint: ["/bin/scripts/startdb.sh"]
    env_file:
      - db.env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - zucchini_wp_html:/var/www/html
      - ./data/wordpress/backup:/var/backups
      - ./scripts:/bin/scripts
    restart: always
    entrypoint: ["/bin/scripts/startwordpress.sh"]
    env_file:
      - wordpress.env

volumes:
  zucchini_db_data: 
    external: true
  zucchini_wp_html:
    external: true
